# Generated by Django 4.0.3 on 2022-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('cpf_cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(max_length=4)),
                ('nome_completo', models.CharField(max_length=150)),
                ('whatsapp', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('complemento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=150)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('potencia', models.IntegerField()),
            ],
        ),
    ]
