# Generated by Django 4.0.1 on 2022-04-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lladmin', '0004_remove_cliente_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
