# Generated by Django 4.0.1 on 2022-04-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lladmin', '0005_cliente_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='anexos',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
