# Generated by Django 4.0.1 on 2022-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lladmin', '0006_cliente_anexos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
    ]
