# Generated by Django 4.0.1 on 2022-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lladmin', '0007_alter_cliente_anexos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='anexos',
            field=models.CharField(default=None, max_length=950),
        ),
    ]
