# Generated by Django 4.0.1 on 2022-05-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lladmin', '0008_alter_cliente_anexos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='anexos',
            field=models.CharField(max_length=950),
        ),
        migrations.CreateModel(
            name='contratos',
            fields=[
                ('cpf_cnpj_contrato', models.CharField(max_length=14)),
                ('conta_contrato', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cpf_cnpj_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lladmin.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ref', models.DateField()),
                ('consumo', models.IntegerField()),
                ('contra_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lladmin.contratos')),
            ],
        ),
    ]
