# Generated by Django 4.0.1 on 2022-05-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lladmin', '0009_alter_cliente_anexos_contratos_contas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contas',
            new_name='conta',
        ),
        migrations.RenameModel(
            old_name='contratos',
            new_name='contrato',
        ),
    ]
