# Generated by Django 4.0.1 on 2022-05-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lladmin', '0010_rename_contas_conta_rename_contratos_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='contra_contrato',
            new_name='conta_contrato',
        ),
        migrations.AlterField(
            model_name='conta',
            name='consumo',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='conta',
            name='data_ref',
            field=models.DateField(default=None),
        ),
    ]
