# Generated by Django 4.0.1 on 2022-05-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lladmin', '0011_rename_contra_contrato_conta_conta_contrato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='conta_contrato',
            new_name='conta',
        ),
    ]
