# Generated by Django 4.0.1 on 2022-06-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lladmin', '0012_rename_conta_contrato_conta_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='consumo',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cpf_cnpj_contrato',
            field=models.CharField(default=None, max_length=14),
        ),
        migrations.DeleteModel(
            name='conta',
        ),
    ]
